# Generated by Django 6.0.1 on 2026-05-20 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickethistory',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='tickethistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='tickethistory',
            name='new_status',
        ),
        migrations.RemoveField(
            model_name='tickethistory',
            name='old_status',
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(default='History Added', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='performed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.ticket'),
        ),
    ]
