# Generated by Django 6.0.1 on 2026-05-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_rename_timestamp_tickethistory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='escalation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
