# Generated by Django 6.0.3 on 2026-05-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_tickethistory_performed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
